### PR TITLE
Bls unemployment insurance claims pipeline

### PR DESCRIPTION
**Pull request by oportusgonzalo**

### CODE REVIEW

**Comment by oportusgonzalo** [comment]
Pipelines created in order to achieve our goal to store BLS Unemployment Insurance Claims data in our databases.

**Comment by oportusgonzalo** [comment]
@innerstage I missed pipelines for dimensions. I'll check that next week as a priority.

**Comment by innerstage** [comment]
I tried to run the pipeline on local, but I got the following error:

```
clickhouse_driver.errors.TypeMismatchError: Code: 53. Type mismatch in VALUES section. Expected String got <class 'pandas._libs.tslibs.timestamps.Timestamp'>: 2020-08-08 00:00:00 for column "week_ended".
```

I think an easy solution to this is to define the `dtypes` on the `LoadStep`, if it doesn't work, you need to make sure the column is cast to the appropriate type before ingesting. It looks good altogether, good job! The error should be an easy fix, and then we'll be ready to merge it 😉

**Comment by innerstage** [comment]
Hey @oportusgonzalo, I still get the same error when trying to ingest on the server with the latest changes:

```
clickhouse_driver.errors.TypeMismatchError: Code: 53. Type mismatch in VALUES section. Expected String got <class 'pandas._libs.tslibs.timestamps.Timestamp'>: 2020-08-08 00:00:00 for column "week_ended".
```

I think the solution you wrote only works on your machine, it's better if you test it with Docker locally. It would take a Clickhouse container + a Python container. Or maybe you could work directly on the VM since it's not on production yet, you just need to use Git on the command line for that.

**Comment by innerstage** [comment]
Hey @oportusgonzalo, before I create a cron job for this on the Tesseract backend please delete any code/notes inside the branch that are not related to your ETL process, we will have the original on the `main` branch, so it's not a problem. Also, I checked some instructions on how to run the new ETL, but it says that we still need to download the source files manually, what is the goal of the new pipeline? How is it different from the previous ETL pipeline?

**Comment by oportusgonzalo** [comment]
Hi @innerstage, first of all, I think notes written inside the ETL process are helpful to understand the pipeline itself as there are future modifications that will be done and other developers that will come to make changes. Even for me are helpful as you may not remember why you did some stuff. 

Secondly, there are huge differences in the process. The goal of the changes wasn't to automatize the download of the files (which should be our next goal) but to automatize the transformation and cleaning of the table extracted from the pdf (by tabula), because before it was made manually. And also, to create the pipelines that allow us to ingest the data into our databases.

As you may also think, this process can be much better, but we need more time for that. Because of that, the future goal in to automatize the download and run the process efectively.

**Comment by innerstage** [comment]
Thanks! OK, since this pipeline is not fully automated, it doesn't make sense to create a cron job for it and it shouldn't be merged at all. This work should remain in this same branch until the pipeline is completed, just make sure each pipeline (dims and fact table) can run single-handedly on a local dev environment, then you can open a new PR for me to review, I'm closing this one.

**Pull request closed without merging**
